### ISSUE TITLE
Diviser le getstock en 3 commandes

### ISSUE THREAD

**Issue by Antoine57437** [TanguyLe/MagicPriceUpdater#25]
- getstock : sauvegarde le stock dans un csv
- getdata : télécharge le fichier de données de chaque carte
- calculate : génère le csv utilisé pour update à l’aide des données au dessus de de la stratégie 

Chaque étape prend de plus en plus de temps (5 min pour getstock, 2 à 4 jours pour mettre à jour les datas). Ca m’arrive souvent de devoir tout faire alors que je veux juste faire l’une de ces étapes. 
L’api mkm est de plus en plus généreuse en erreur 429 donc je peux plus getstock à volonté pour tester ce que je code.

D'où l'idée de séparer la commande en 3

**Comment by TanguyLe** [comment]
Implémenté, je te laisse regarder la doc
