### ISSUE TITLE
Arreter le get data quand on prend des 429 à répétition :

### ISSUE THREAD

**Issue by Antoine57437** [TanguyLe/MagicPriceUpdater#29]
Quand je laisse tourner l’ordi la nuit, le programme tourne plusieurs heures encore même si on a atteint la limite quotidienne. C’est pas gênant en soit, donc si c’est compliqué à faire, osef.

**Comment by TanguyLe** [comment]
Fait dans la 0.7.0.
A noter que j'arrête si:
- 429
- Nombre max de requêtes atteint

Mais j'ai bcp de mal à la tester et je me demande si il me renvoient vraiment le nombre max de requêtes sur les query product, je suis pas sûr. Donc potentiellement ça ne fonctionne pas :)
